<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Database Connection Name
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the database connections below you wish
    | to use as your default connection for all database work. Of course
    | you may use many connections at once using the Database library.
    |
    */

    'default' => env('DB_CONNECTION', 'mysql'),

    /*
    |--------------------------------------------------------------------------
    | Database Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the database connections setup for your application.
    | Of course, examples of configuring each database platform that is
    | supported by Laravel is shown below to make development simple.
    |
    |
    | All database work in Laravel is done through the PHP PDO facilities
    | so make sure you have the driver for your particular database of
    | choice installed on your machine before you begin development.
    |
    */

    'connections' => [

//        'sqlite' => [
//            'driver' => 'sqlite',
//            'database' => env('DB_DATABASE', database_path('database.sqlite')),
//            'prefix' => '',
//        ],

       'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '172.31.5.53'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'UTGAPI'),
            'username' => env('DB_USERNAME', 'utg_develop'),
            'password' => env('DB_PASSWORD', '4=EcYQ87*{'),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'OmniDialer' => [
            'driver' => 'mysql',
            'host' => '10.26.144.25',
            'port' => '3306',
            'database' => 'custom_view',
            'username' => 'AnkitK',
            'password' => 'DC2fzk6rMWBSrVpf',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
       'Intelling' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '172.31.5.53'),
            'port' => env('DB_PORT', '3306'),
            'database' => 'intelling',
            'username' => env('DB_USERNAME', 'utg_develop'),
            'password' => env('DB_PASSWORD', '4=EcYQ87*{'),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'Intelling_DW' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '172.31.5.53'),
            'port' => env('DB_PORT', '3306'),
            'database' => 'Intelling_DW',
            'username' => env('DB_USERNAME', 'utg_develop'),
            'password' => env('DB_PASSWORD', '4=EcYQ87*{'),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
       'O2Inbound' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '172.31.5.53'),
            'port' => env('DB_PORT', '3306'),
            'database' => 'O2Inbound',
            'username' => env('DB_USERNAME', 'utg_develop'),
            'password' => env('DB_PASSWORD', '4=EcYQ87*{'),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
       'O2Combine' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '172.31.5.53'),
            'port' => env('DB_PORT', '3306'),
            'database' => 'O2Combine',
            'username' => env('DB_USERNAME', 'utg_develop'),
            'password' => env('DB_PASSWORD', '4=EcYQ87*{'),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'MainDialer' => [
            'driver' => 'mysql',
            'host' => '10.23.136.6',
            'port' => '3306',
            'database' => 'custom_view',
            'username' => 'AnkitK',
            'password' => 'DC2fzk6rMWBSrVpf',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'SwitchExpert' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'SwitchExperts',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'SE_RightDea' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'SE_RightDea',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'IntellingScriptDB' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'IntellingScriptDB',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'mysql8' => [
            'driver' => 'mysql',
            'host' => '10.29.104.6',
            'port' => env('DB_PORT', '3306'),
            'database' => 'Intelling',
            'username' => 'UTGIntelling',
            'password' => 'UTG1nt3ll1ng',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'pgsql' => [
            'driver' => 'pgsql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],
        'sqlsrv' => [
            'driver' => 'sqlsrv',
            'host' => '192.168.10.16',
            'port' => '1433',
            'database' => 'CampaignManager',
            'username' => 'SCR',
            'password' => 'IntTech0715',
            'charset' => 'utf8',
            'prefix' => '',
        ],
        'sqlsrv1' => [
            'driver' => 'sqlsrv',
            'host' => '172.101.10.82',
            'port' => '1433',
            'database' => 'IntellingDev',
            'username' => 'sa',
            'password' => 'Intelling2014',
            'charset' => 'utf8',
            'prefix' => '',
        ],
        'mysql2' => [
            'driver' => 'mysql',
            'host' => '10.29.104.6',
            'port' => env('DB_PORT', '3306'),
            'database' => 'custom_view',
            'username' => 'UTGIntelling',
            'password' => 'UTG1nt3ll1ng',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'mysql1' => [
            'driver' => 'mysql',
            'host' => '10.23.101.5',
            'port' => '3306',
            'database' => 'asterisk',
            'username' => 'Intelling',
            'password' => '1nt3ll1ng',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'mysql3' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'FORD',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'mysql30' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'UKFORD',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'switch_experts_in' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'SwitchExpertIN',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'SwitchO2' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'SwitchO2',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'sqlsrv2' => [
            'driver' => 'sqlsrv',
            'host' => '192.168.10.16',
            'port' => '1433',
            'database' => 'NBSLeadGen',
            'username' => 'SCR',
            'password' => 'IntTech0715',
            'charset' => 'utf8',
            'prefix' => '',
        ],
        'mysql5' => [
            'driver' => 'mysql',
            'host' => '10.29.104.6',
            'port' => env('DB_PORT', '3306'),
            'database' => 'Intelling',
            'username' => 'UTGIntelling',
            'password' => 'UTG1nt3ll1ng',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'sqlsrv3' => [
            'driver' => 'sqlsrv',
            'host' => '192.168.10.16',
            'port' => '1433',
            'database' => 'O2Cohort',
            'username' => 'SCR',
            'password' => 'IntTech0715',
            'charset' => 'utf8',
            'prefix' => '',
        ],
        'sqlsrv4' => [
            'driver' => 'sqlsrv',
            'host' => 'kombea',
            //'port' => '1433',
            'database' => 'kombea',
            'username' => 'Sa',
            'password' => '[Kombea]',
            'charset' => 'utf8',
            'prefix' => '',
        ],
        'mysql6' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'TalkingPeople',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'mysql7' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'EntireMedia',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'mysql10' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'switchexpertEnergy',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ], 'mysql_asterisk' => [
            'driver' => 'mysql',
            'host' => '10.29.104.6',
            'port' => '3306',
            'database' => 'asterisk',
            'username' => 'Intelling',
            'password' => '1nt3ll1ng',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'mysql_api' => [
            'driver' => 'pgsql',
            'host' => '52.212.12.136',
            'port' => '5433',
            'database' => 'fusionpbx',
            'username' => 'fusionpbx',
            'password' => 'PasswordSuperSecureFusionPBX',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'emerging_media' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'EmergingMedia',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'O2Combine' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'O2Combine',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'IScript' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'IScriptbelfastvoice',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'mysqlCCI' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'CCIINBOUND',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'mysql_avatar_hotkey' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'avatar_hotkey',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'mysql_118_Ford' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => '118_Ford',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'mysql_dual_energy' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'Dual_Energy',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'main_dialer_asterisk' => [
            'driver' => 'mysql',
            'host' => '10.29.104.6',
            'port' => '3306',
            'database' => 'asterisk',
            'username' => 'UTGIntelling',
            'password' => 'UTG1nt3ll1ng',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'avatar_dialer' => [
            'driver' => 'mysql',
            'host' => '10.28.128.5',
            'port' => '3306',
            'database' => 'custom_view',
            'username' => 'AnkitK',
            'password' => 'Intelling123',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'PrisionDialer' => [
            'driver' => 'mysql',
            'host' => '10.23.101.9',
            'port' => '3306',
            'database' => 'custom_view',
            'username' => 'akumar',
            'password' => '4kum4r',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'my_offer' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'MyOffer',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        '118Belfast' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => '118_Belfast',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        '118FordRelaunch' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => '118_Ford_Relaunch',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'ClearAssist' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'ClearAssist',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'Toto' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'Toto',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'CrudSystem' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'practice_developer',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'Cogenthub' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'Cogenthub',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'AsteriskDialer' => [
            'driver' => 'mysql',
            'host' => '10.68.122.48',
            'port' => '3306',
            'database' => 'asterisk',
            'username' => 'akumar',
            'password' => '4=EcYQ87*{',
            'strict' => true,
            'engine' => null,
        ],
        'TransformHotkey' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'Transform_Hotkey',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'B2BEnergyCEDLeadGen' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'B2BEnergyCEDLeadGen',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'Bite' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'Bite',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'HomeImprove' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'HomeImprove',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'TalkTalkO2Inbound' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'TalkTalkO2Inbound',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'ShopBlocks' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'ShopBlocks',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'MortgageClaim' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'MortgageClaim',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'Canvessor' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'Canvessor',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'Mycover' => [
            'driver' => 'mysql',
            'host' => '10.68.122.52',
            'port' => '3306',
            'database' => 'asterisk',
            'username' => 'akumar',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'BiteAPI' => [
            'driver' => 'mysql',
            'host' => '10.68.120.50',
            'port' => '3306',
            'database' => 'asterisk',
            'username' => 'akumar',
            'password' => '4=EcYQ87*{',
            'strict' => true,
            'engine' => null,
        ],
        'BiteAPI2' => [
            'driver' => 'mysql',
            'host' => '52.51.48.253',
//            'host' => '52.208.109.170',
            'port' => '3306',
            'database' => 'asterisk',
            'username' => 'akumar',
            'password' => '4=EcYQ87*{',
            'strict' => true,
            'engine' => null,
        ],
        'SE_RightDea' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'SE_RightDea',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'UTGAPI' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'UTGAPI',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'O2PostIntelling' => [
            'driver' => 'mysql',
            'host' => '10.68.120.8',
            'port' => '3306',
            'database' => 'intelling',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'ConsumerMaster' => [
            'driver' => 'mysql',
            'host' => '172.31.5.53',
            'port' => '3306',
            'database' => 'ConsumerMaster',
            'username' => 'utg_develop',
            'password' => '4=EcYQ87*{',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'NewConnex' => [
            'driver' => 'mysql',
            'host' => '10.23.136.6',
            'port' => '3306',
            'database' => 'custom_view',
            'username' => 'AnkitK',
            'password' => 'DC2fzk6rMWBSrVpf',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'NewDialer' => [
            'driver' => 'mysql',
            'host' => '10.23.136.6',
            'port' => '3306',
            'database' => 'custom_view',
            'username' => 'AnkitK',
            'password' => 'DC2fzk6rMWBSrVpf',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'MainDialerIntelling' => [
            'driver' => 'mysql',
            'host' => '10.23.136.6',
            'port' => '3306',
            'database' => 'Intelling',
            'username' => 'AnkitK',
            'password' => 'DC2fzk6rMWBSrVpf',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ]

//        'pgsql' => [
//            'driver' => 'pgsql',
//            'host' => env('DB_HOST', '127.0.0.1'),
//            'port' => env('DB_PORT', '5432'),
//            'database' => env('DB_DATABASE', 'forge'),
//            'username' => env('DB_USERNAME', 'forge'),
//            'password' => env('DB_PASSWORD', ''),
//            'charset' => 'utf8',
//            'prefix' => '',
//            'schema' => 'public',
//            'sslmode' => 'prefer',
//        ],

//        'sqlsrv' => [
//            'driver' => 'sqlsrv',
//            'host' => env('DB_HOST', 'localhost'),
//            'port' => env('DB_PORT', '1433'),
//            'database' => env('DB_DATABASE', 'forge'),
//            'username' => env('DB_USERNAME', 'forge'),
//            'password' => env('DB_PASSWORD', ''),
//            'charset' => 'utf8',
//            'prefix' => '',
//        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk haven't actually been run in the database.
    |
    */

    'migrations' => 'migrations',

    /*
    |--------------------------------------------------------------------------
    | Redis Databases
    |--------------------------------------------------------------------------
    |
    | Redis is an open source, fast, and advanced key-value store that also
    | provides a richer set of commands than a typical key-value systems
    | such as APC or Memcached. Laravel makes it easy to dig right in.
    |
    */

    'redis' => [

        'client' => 'predis',

        'default' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 0,
        ],

    ],

];
